---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 178.154.220.131
      ansible_private_key_file: ~/.ssh/id_ed25519
    jenkins-agent-01:
      ansible_host: 158.160.126.27
      ansible_private_key_file: ~/.ssh/id_ed25519
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: user